/// قاموس الترجمة الشامل لتطبيق LUMCAL APP
/// يدعم اللغة العربية 100% واللغة الإنجليزية 100%
class AppStrings {
  static String get(String key, bool isArabic) {
    if (isArabic) {
      return _ar[key] ?? _en[key] ?? key;
    } else {
      return _en[key] ?? _ar[key] ?? key;
    }
  }

  static const Map<String, String> _ar = {
    'app_title': 'LUMCAL APP',
    'app_subtitle': 'by BOUGHABA ABDESSAMIE',
    'lang_toggle': 'EN',
    
    // التبويبات
    'tab_lighting': 'الإضاءة',
    'tab_cable': 'مقطع الكابل',
    'tab_short_circuit': 'تيار القصر والفصل',
    'nav_calculator': 'الحاسبة',
    'nav_standards': 'دليل معايير الإضاءة',
    'nav_project': 'مشروع المنزل',

    // أقسام الشاشات
    'sec_room_data': '1. بيانات الغرفة والأبعاد',
    'sec_target_lux': '2. شدة الإضاءة المطلوبة (Lux)',
    'sec_bulb_specs': '3. خصائص اللمبة المختارة',
    'sec_supply_system': '1. نظام التغذية والجهد الكهربائي',
    'sec_load_data': '2. بيانات الحمل الكهربائي',
    'sec_cable_insulation': '3. مواصفات الكابل ونوع العزل (IEC Standards)',
    'sec_length_drop': '4. طول الخط وهبوط الجهد المسموح',
    'sec_installation_ambient': '5. طريقة التمديد والظروف المحيطة',
    'sec_cb_specs': '6. مواصفات القاطع الكهربائي (Circuit Breaker)',

    // حقول ونصوص الإنارة
    'lighting_title': 'حاسبة الإضاءة المنزلية',
    'lighting_banner': 'أدخل أبعاد الغرفة وشدة الإضاءة لحساب عدد اللمبات واستهلاك الطاقة واقتراح السلك والقاطع المناسب.',
    'room_name': 'اسم الدائرة / الفراغ:',
    'room_name_label': 'اسم الغرفة',
    'custom_room_label': 'اكتب اسم الغرفة المخصص',
    'custom_room_hint': 'مثال: صالة الاستقبال',
    'length_m': 'الطول (متر):',
    'length_label': 'الطول (بالمتر)',
    'length_hint': 'مثال: 5.0',
    'width_m': 'العرض (متر):',
    'width_label': 'العرض (بالمتر)',
    'width_hint': 'مثال: 4.0',
    'meter_unit': 'م',
    'target_lux': 'شدة الإضاءة المطلوبة (Lux):',
    'lux_label': 'شدة الإضاءة (Lux)',
    'lux_hint': 'مثال: 150',
    'lux_unit': 'لوكس',
    'lux_helper': 'يمكنك الاختيار السريع من المعايير الشائعة أدناه',
    'bulb_presets_label': 'خيارات لمبات LED جاهزة:',
    'bulb_lumen': 'لومين اللمبة (lm):',
    'lumen_label': 'تدفق اللمبة (Lumen)',
    'lumen_hint': '806',
    'lumen_unit': 'lm',
    'bulb_watt': 'قدرة اللمبة (Watt):',
    'watt_label': 'قدرة اللمبة (Watt)',
    'watt_hint': '9',
    'watt_unit': 'W',
    'required_field': 'مطلوب',
    'invalid_value': 'قيمة غير صالحة',
    'enter_lux': 'يرجى إدخال شدة الإضاءة',
    'enter_room_name': 'يرجى إدخال اسم الغرفة',
    'btn_calculate_lighting': 'احسب الإضاءة المطلوبة',
    'calculate': 'حساب وتحديث',
    'lighting_results': 'نتائج حساب الإضاءة',
    'room_area': 'المساحة',
    'total_lumens': 'إجمالي اللومين',
    'bulbs_count': 'عدد اللمبات',
    'total_watt': 'الاستهلاك الإجمالي',
    'wire_recommendation': 'توصية السلك والقاطع',
    'btn_size_cable': 'حساب الكابل ⬅',
    'btn_add_to_project': 'إضافة لمشروع المنزل',
    'quick_project_bar_title': 'مشروع المنزل الحالي',
    'quick_project_bar_view': 'عرض المشروع',
    'rooms_word': 'غرف',
    'total_power': 'إجمالي القدرة:',
    'watt_word': 'واط',
    'bulbs_word': 'اللمبات:',

    // غرف الإنارة
    'room_living': 'غرفة المعيشة',
    'room_bedroom': 'غرفة النوم',
    'room_kitchen': 'المطبخ',
    'room_office': 'المكتب / الدراسة',
    'room_bath': 'الحمامات',
    'room_corridor': 'الممرات والمداخل',
    'room_dining': 'غرفة الطعام',
    'room_other': 'أخرى (مخصص)',

    // الكابلات
    'cable_title': 'حساب مقطع السلك والكابل (IEC)',
    'cable_banner': 'حساب مقاطع الكابلات وفق معايير IEC 60364-5-52 الدقيقة مع مراعاة العزل، طريقة التمديد، والحرارة والتجاور.',
    'circuit_name_for_proj': 'اسم الدائرة / الفراغ (لربطه بالمشروع):',
    'circuit_name_hint': 'مثلاً: غرفة المعيشة أو اللوحة الرئيسية',
    'phase_system': 'نظام الأطوار:',
    'phase_system_label': 'نظام الأطوار (Phase)',
    'voltage_v': 'الجهد (Voltage V):',
    'voltage_label': 'الجهد (Voltage)',
    'load_value': 'قيمة الحمل:',
    'load_value_label': 'قيمة الحمل',
    'load_type': 'نوع الحمل:',
    'load_type_label': 'نوع الحمل',
    'power_factor': 'معامل القدرة (cos φ):',
    'power_factor_label': 'معامل القدرة (Power Factor - cos φ)',
    'power_factor_helper': 'قيمة بين 0.70 إلى 1.00 (افتراضي: 0.85)',
    'cable_length_m': 'طول الكابل (متر):',
    'cable_length_label': 'طول الكابل (بالمتر)',
    'conductor_material': 'مادة الموصل:',
    'material_label': 'مادة الموصل',
    'insulation_type': 'نوع العزل:',
    'insulation_label': 'نوع العزل (Insulation)',
    'installation_method': 'طريقة التمديد:',
    'method_label': 'طريقة التمديد (Installation Method)',
    'ambient_temp_label': 'درجة حرارة المحيط (°C)',
    'soil_temp_label': 'درجة حرارة التربة (°C)',
    'temperature_c': 'الحرارة (°C):',
    'grouping_circuits': 'التجاور (دوائر):',
    'grouping_label': 'عدد الدوائر المتجاورة (Grouping)',
    'core_type_label': 'نوع الكابل (Cores)',
    'max_delta_v_pct': 'أقصى هبوط جهد ΔV (%):',
    'max_deltav_label': 'أقصى هبوط جهد مسموح (%)',
    'total_k_factor': 'معامل التصحيح الكلي:',
    'cable_results': 'التوصية الهندسية للمقطع',
    'recommended_section': 'المقطع المعتمد الموصى به:',
    'recommended_cable_section': 'مقطع الكابل الموصى به هندسياً:',
    'section_safety_note': 'يحقق كفاءة التحمل الحراري والأمان لهبوط الجهد معاً',
    'design_current_ib': 'تيار التصميم (Ib)',
    'min_section_delta_v': 'أدنى مقطع لهبوط الجهد (Min S)',
    'final_capacity_iz': 'سعة تحمل الكابل (Iz)',
    'recommended_breaker': 'القاطع المناسب',
    'actual_delta_v': 'هبوط الجهد الفعلي (Actual ΔV)',
    'btn_check_sc': 'فحص القصر ⬅',
    'btn_calculate_cable': 'حساب مقطع الكابل',
    'btn_reset_defaults': 'إعادة تعيين',
    'overcapacity_title': 'الحمل يتجاوز سعة أكبر كابل مفرد في الجدول (240 mm²)',
    'parallel_cables_advice': 'يُنصح بتمديد كابلين أو أكثر على التوازي (Parallel Cables) لتوزيع الحمل.',

    // تيار القصر
    'sc_title': 'تيار القصر ومنحنيات الفصل (IEC)',
    'sc_banner': 'حساب تيار القصر وفحص التحمل الحراري للكابل واختيار منحنى الفصل المناسب (Curves B, C, D, K, Z).',
    'sc_name': 'اسم الدائرة / الفراغ (لربطه بالمشروع):',
    'sc_phase': 'نظام الأطوار والجهد:',
    'sc_len': 'طول الكابل (متر):',
    'sc_matins': 'مادة الموصل ونوع العزل:',
    'upstream_isc': 'تيار قصر المنبع (Isc source kA):',
    'cable_section_mm2': 'مقطع الكابل (mm²):',
    'clearing_time_s': 'زمن فصل القاطع (t بالثواني):',
    'cb_specs_title': 'مواصفات القاطع الكهربائي (Circuit Breaker):',
    'rated_current_in': 'التيار الاسمي للقاطع (In):',
    'tripping_curve': 'منحنى الفصل (Tripping Curve):',
    'sc_results_title': 'نتائج فحص تيار القصر والفصل',
    'max_fault_current': 'أقصى تيار قصر (Isc max)',
    'min_fault_current': 'أدنى تيار قصر (Isc min)',
    'thermal_withstand_smin': 'التحمل الحراري (Min S req)',
    'max_permissible_length': 'أقصى طول مسموح (L max)',
    'mag_status_title': 'حالة الفصل المغناطيسي اللحظي',
    'mag_safe_trip': 'فصل لحظي آمن (t ≤ 0.1s) ✔',
    'mag_warning_trip': 'تحذير: لا يضمن فصلاً لحظياً ⚠️',
    'thermally_safe': 'الكابل محمي حرارياً ✔',
    'thermally_unsafe': 'تحذير: مقطع الكابل ضعيف حرارياً! ⚠️',

    // مشروع المنزل
    'project_summary_title': 'الملخص الإجمالي لمشروع المنزل',
    'unified_items': 'عناصر موحدة',
    'total_area': 'إجمالي المساحة',
    'total_load': 'إجمالي الحمل',
    'circuits_count': 'الدوائر والكابلات',
    'breakers_count': 'القواطع والحماية',
    'project_items_title': 'عناصر ودوائر المشروع المدمجة:',
    'btn_download_pdf': 'تحميل تقرير PDF بالإنجليزية',
    'btn_add_another': '+ إضافة دائرة أخرى',
    'item_added_success': 'تمت إضافة العنصر بنجاح إلى مشروع المنزل!',
    'confirm_clear_title': 'مسح جميع العناصر؟',
    'confirm_clear_msg': 'هل أنت متأكد من رغبتك في حذف جميع عناصر وغرف المشروع الموحدة؟',
    'cancel': 'إلغاء',
    'clear_all': 'مسح الكل',
    'empty_project_title': 'مشروع المنزل فارغ حالياً',
    'empty_project_desc': 'يمكنك حساب الإنارة أو مقطع الكابل أو تيار القصر والضغط على "إضافة لمشروع المنزل" لدمجها هنا.',
    'start_calculations': 'بدء الحساب وإضافة عناصر',

    // دليل المعايير
    'standards_title': 'دليل معايير الإضاءة',
    'standards_banner': 'المرجع الهندسي الدولي لمستويات الإضاءة (CIBSE / EN 12464) ودرجات حرارة الألوان (Kelvin).',
    'standards_list_title': 'المعايير الموصى بها لكل فراغ منزلي:',
    'standard_applied_snackbar': 'تم تطبيق معايير في الحاسبة',
  };

  static const Map<String, String> _en = {
    'app_title': 'LUMCAL APP',
    'app_subtitle': 'by BOUGHABA ABDESSAMIE',
    'lang_toggle': 'عربي',

    // Tabs
    'tab_lighting': 'Lighting',
    'tab_cable': 'Cable Sizing',
    'tab_short_circuit': 'Short-Circuit & CB',
    'nav_calculator': 'Calculator',
    'nav_standards': 'Lighting Standards',
    'nav_project': 'Home Project',

    // Section headers
    'sec_room_data': '1. Room Data & Dimensions',
    'sec_target_lux': '2. Target Illuminance (Lux)',
    'sec_bulb_specs': '3. Selected Bulb Specifications',
    'sec_supply_system': '1. Power Supply System & Voltage',
    'sec_load_data': '2. Electrical Load Data',
    'sec_cable_insulation': '3. Cable Specifications & Insulation (IEC)',
    'sec_length_drop': '4. Cable Length & Permissible Voltage Drop',
    'sec_installation_ambient': '5. Installation Method & Ambient Conditions',
    'sec_cb_specs': '6. Circuit Breaker Specifications (MCB)',

    // Lighting fields & texts
    'lighting_title': 'Lighting Calculator',
    'lighting_banner': 'Enter room dimensions and target illuminance to calculate bulb count, power consumption, and recommended wiring.',
    'room_name': 'Circuit / Room Name:',
    'room_name_label': 'Room Name',
    'custom_room_label': 'Enter Custom Room Name',
    'custom_room_hint': 'e.g. Reception Hall',
    'length_m': 'Length (m):',
    'length_label': 'Length (meters)',
    'length_hint': 'e.g. 5.0',
    'width_m': 'Width (m):',
    'width_label': 'Width (meters)',
    'width_hint': 'e.g. 4.0',
    'meter_unit': 'm',
    'target_lux': 'Required Illuminance (Lux):',
    'lux_label': 'Illuminance (Lux)',
    'lux_hint': 'e.g. 150',
    'lux_unit': 'Lux',
    'lux_helper': 'Quickly select from standard recommendations below',
    'bulb_presets_label': 'Quick LED Bulb Presets:',
    'bulb_lumen': 'Bulb Lumens (lm):',
    'lumen_label': 'Bulb Luminous Flux (Lumen)',
    'lumen_hint': '806',
    'lumen_unit': 'lm',
    'bulb_watt': 'Bulb Wattage (W):',
    'watt_label': 'Bulb Power (Watt)',
    'watt_hint': '9',
    'watt_unit': 'W',
    'required_field': 'Required',
    'invalid_value': 'Invalid value',
    'enter_lux': 'Please enter illuminance',
    'enter_room_name': 'Please enter room name',
    'btn_calculate_lighting': 'Calculate Lighting',
    'calculate': 'Calculate & Update',
    'lighting_results': 'Lighting Calculation Results',
    'room_area': 'Room Area',
    'total_lumens': 'Total Lumens',
    'bulbs_count': 'Bulb Count',
    'total_watt': 'Total Load',
    'wire_recommendation': 'Recommended Wire & Breaker',
    'btn_size_cable': 'Size Cable ⬅',
    'btn_add_to_project': 'Add to Home Project',
    'quick_project_bar_title': 'Current Home Project',
    'quick_project_bar_view': 'View Project',
    'rooms_word': 'Rooms',
    'total_power': 'Total Power:',
    'watt_word': 'W',
    'bulbs_word': 'Bulbs:',

    // Room Presets
    'room_living': 'Living Room',
    'room_bedroom': 'Bedroom',
    'room_kitchen': 'Kitchen',
    'room_office': 'Office / Study',
    'room_bath': 'Bathroom',
    'room_corridor': 'Hallways & Corridors',
    'room_dining': 'Dining Room',
    'room_other': 'Other (Custom)',

    // Cables
    'cable_title': 'Cable Sizing Calculator (IEC)',
    'cable_banner': 'Precise cable sizing per IEC 60364-5-52 factoring in insulation, installation method, temperature, and grouping.',
    'circuit_name_for_proj': 'Circuit / Feeder Name (for project):',
    'circuit_name_hint': 'e.g. Living Room or Main Feeder',
    'phase_system': 'Phase System:',
    'phase_system_label': 'Phase System',
    'voltage_v': 'Voltage (V):',
    'voltage_label': 'Voltage',
    'load_value': 'Load Value:',
    'load_value_label': 'Load Value',
    'load_type': 'Load Type:',
    'load_type_label': 'Load Type',
    'power_factor': 'Power Factor (cos φ):',
    'power_factor_label': 'Power Factor (cos φ)',
    'power_factor_helper': 'Between 0.70 and 1.00 (default: 0.85)',
    'cable_length_m': 'Cable Length (m):',
    'cable_length_label': 'Cable Length (meters)',
    'conductor_material': 'Conductor Material:',
    'material_label': 'Conductor Material',
    'insulation_type': 'Insulation Type:',
    'insulation_label': 'Insulation Type',
    'installation_method': 'Installation Method:',
    'method_label': 'Installation Method',
    'ambient_temp_label': 'Ambient Temperature (°C)',
    'soil_temp_label': 'Soil Temperature (°C)',
    'temperature_c': 'Temperature (°C):',
    'grouping_circuits': 'Grouping (Circuits):',
    'grouping_label': 'Grouping (Circuits)',
    'core_type_label': 'Cable Core Type',
    'max_delta_v_pct': 'Max ΔV (%):',
    'max_deltav_label': 'Max Permissible ΔV (%)',
    'total_k_factor': 'Total Correction Factor:',
    'cable_results': 'Recommended Cable Cross-Section',
    'recommended_section': 'Recommended Standard Section:',
    'recommended_cable_section': 'Recommended Standard Cable Section:',
    'section_safety_note': 'Satisfies both thermal ampacity and voltage drop criteria',
    'design_current_ib': 'Design Current (Ib)',
    'min_section_delta_v': 'Min Section for ΔV (Min S)',
    'final_capacity_iz': 'Cable Ampacity (Iz)',
    'recommended_breaker': 'Recommended Breaker',
    'actual_delta_v': 'Actual Voltage Drop (ΔV)',
    'btn_check_sc': 'Check Short-Circuit ⬅',
    'btn_calculate_cable': 'Calculate Cable Size',
    'btn_reset_defaults': 'Reset Defaults',
    'overcapacity_title': 'Load exceeds single cable table maximum (240 mm²)',
    'parallel_cables_advice': 'Multiple parallel cables are recommended to distribute load.',

    // Short-Circuit
    'sc_title': 'Short-Circuit & Tripping Curves (IEC)',
    'sc_banner': 'Calculate fault currents, verify thermal withstand, and select tripping curve (Curves B, C, D, K, Z).',
    'sc_name': 'Circuit / Feeder Name (for project):',
    'sc_phase': 'Phase System & Voltage:',
    'sc_len': 'Cable Length (m):',
    'sc_matins': 'Conductor & Insulation:',
    'upstream_isc': 'Upstream Fault Current (Isc source kA):',
    'cable_section_mm2': 'Cable Section (mm²):',
    'clearing_time_s': 'Clearing Time (t in seconds):',
    'cb_specs_title': 'Circuit Breaker Specifications:',
    'rated_current_in': 'Rated Current (In):',
    'tripping_curve': 'Tripping Curve:',
    'sc_results_title': 'Short-Circuit & Protection Results',
    'max_fault_current': 'Max Fault Current (Isc max)',
    'min_fault_current': 'Min Fault Current (Isc min)',
    'thermal_withstand_smin': 'Thermal Withstand (Min S req)',
    'max_permissible_length': 'Max Permissible Length (L max)',
    'mag_status_title': 'Instantaneous Magnetic Trip Status',
    'mag_safe_trip': 'Instantaneous Trip OK (t ≤ 0.1s) ✔',
    'mag_warning_trip': 'Warning: No Instantaneous Trip ⚠️',
    'thermally_safe': 'Thermally Protected ✔',
    'thermally_unsafe': 'Warning: Thermal Limit Exceeded! ⚠️',

    // Project
    'project_summary_title': 'Unified Home Project Summary',
    'unified_items': 'Unified Items',
    'total_area': 'Total Area',
    'total_load': 'Total Load',
    'circuits_count': 'Circuits & Cables',
    'breakers_count': 'Protection & Breakers',
    'project_items_title': 'Unified Project Circuits & Elements:',
    'btn_download_pdf': 'Download English PDF Report',
    'btn_add_another': '+ Add Another Circuit',
    'item_added_success': 'Item added to Home Project successfully!',
    'confirm_clear_title': 'Clear All Items?',
    'confirm_clear_msg': 'Are you sure you want to delete all unified project items?',
    'cancel': 'Cancel',
    'clear_all': 'Clear All',
    'empty_project_title': 'Home Project is Currently Empty',
    'empty_project_desc': 'Calculate lighting, cable sizing, or short-circuit protection and tap "Add to Home Project" to unify them here.',
    'start_calculations': 'Start Calculations',

    // Standards
    'standards_title': 'Lighting Standards Guide',
    'standards_banner': 'International recommended illuminance levels (CIBSE / EN 12464) and color temperatures (Kelvin).',
    'standards_list_title': 'Recommended Standards for Each Space:',
    'standard_applied_snackbar': 'Standards applied to calculator',
  };
}
